# Generated by Django 5.0.7 on 2024-07-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.category', verbose_name='categoria'),
        ),
    ]
