# Generated by Django 5.0.7 on 2024-07-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=8, verbose_name='palabra')),
                ('description', models.CharField(max_length=300, verbose_name='descripcion')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
                ('category', models.CharField(max_length=12, verbose_name='categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
        ),
    ]
