# Generated by Django 5.0.7 on 2024-07-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_category_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='tamanio'),
        ),
    ]
