# Generated by Django 5.0.7 on 2024-07-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_word_word_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.CharField(max_length=360, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='word', verbose_name='imagen'),
        ),
    ]
