# Generated by Django 5.0.7 on 2024-07-28 02:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_category_image_alter_word_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
