# Generated by Django 5.0.7 on 2024-07-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_alter_word_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image_url',
        ),
    ]
