# Generated by Django 5.0.7 on 2024-08-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_created_alter_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='is_resolved',
        ),
    ]
